squawker-django-master/squawker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#The include() function allows referencing other URLconfs.
urlpatterns = [
    url(r'^', include('squawker2.urls')),
    url(r'^admin/', admin.site.urls),
]

squawker-django-master/squawker2/urls.py
from django.conf.urls import url
from . import views

app_name = 'squawker'
urlpatterns = [
               url(r'^$', views.index, name='index'),
               url(r'^add/$', views.add_squawker, name='add'),
               ]

squawker-django-master/squawker2/models.py
from django.db import models

# Create your models here.
from django.db import models


class Squawks(models.Model):
    squawk = models.CharField(max_length=140)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.squawk

squawker-django-master/squawker2/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse
from django.views.generic import RedirectView


from .models import Squawks


def index(request):
    context = {'squawker2_squawks': Squawks.objects.order_by('-id')}
    return render(request, 'index.html', context)


def add_squawker(request):
    s = Squawks(squawk=request.POST['post_text'])
    if len(s.squawk) > 140:
        response.status_code = 400
        response = HttpResponse('Invalid, please restrict your chars <= 140 ')
        return response
    else:
        s.save()
    return index(request)

squawker-django-master/squawker2/templates/index.html
<!DOCTYPE HTML>
<html>
<head>
	<title>Squawker</title>
</head>
<body>
	<!-- Form to post a squawk -->
	<form action="{% url 'squawker:add'%}" method="post">
		<div>
				<label for="msg">Type in your post:</label>
						<br>
                 {% csrf_token %}
				<textarea placeholder="What's going on?" name='post_text' rows='4' cols='80' id="post_text"  maxlength="140"></textarea>
		</div>
		<div class="button">
			<button type="submit">Post</button>
		</div>
	</form>
		<!-- List of sqawks -->
	<div id="squawks">
        <p>Squawks By Time: </p>
		<br>
		{% for entry in squawker2_squawks %}
    		<br>
<!--            <div> hi </div>-->
    		<div>{{ entry.squawk  }}</div>
		{% endfor %}

	</div>

	<br><br>



</body>
</html>